CFLAGS_KERNEL   += -I$(srctree)/arch/mips/xburst/soc-x1000/chip-x1500/$(CONFIG_PRODUCT_NAME)/$(CONFIG_BOARD_NAME)

obj-y       += common/
obj-$(CONFIG_BOARD_X1500_YAK_V10)      += $(CONFIG_BOARD_NAME)/

