LOCAL_PATH := $(my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE=$(KERNEL_TARGET_IMAGE)
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE_PATH := $(OUT_IMAGE_DIR)
LOCAL_MODULE_GEN_BINRARY_FILES= $(KERNEL_IMAGE_PATH)/$(KERNEL_TARGET_IMAGE)
LOCAL_MODULE_CONFIG_FILES:=.config
LOCAL_MODULE_CONFIG= make $(KERNEL_BUILD_CONFIG)
LOCAL_MODULE_COMPILE=make $(KERNEL_TARGET_IMAGE) -j$(MAKE_JLEVEL)
LOCAL_MODULE_COMPILE_CLEAN=make distclean
include $(BUILD_THIRDPART)

