
obj-$(CONFIG_SPI_JZ47XX) += spi_bus.o
obj-$(CONFIG_SOUND) += sound.o

obj-$(CONFIG_I2C_GPIO)          += i2c_bus.o
obj-$(CONFIG_I2C_V12_JZ)       += i2c_bus.o

obj-$(CONFIG_REGULATOR_ACT8600) += regulator.o
obj-$(CONFIG_LCD_KFM701A21_1A)     += lcd-kfm701a21_1a.o
obj-$(CONFIG_LCD_BYD_8991FTGF)		+= lcd-8991.o
obj-$(CONFIG_FB_JZ4775_ANDROID_EPD)	+= mensa-epd.o
obj-$(CONFIG_MTD_NAND_JZ4775)		+= nand-mtd.o
obj-$(CONFIG_MMC)		+= mmc.o
obj-$(CONFIG_BCM4330_RFKILL)		+= bt.o
obj-$(CONFIG_MTD_NAND_MIRCON_ACA)	+= nand_aca.o
obj-$(CONFIG_SOC_CAMERA)     += cim_board.o
obj-y += board_base.o misc.o
