
obj-y += board_base.o misc.o

obj-$(CONFIG_KEYBOARD_GPIO)	+= keyboard_gpio.o
obj-$(CONFIG_JZ_SPI) += spi_bus.o

obj-$(CONFIG_SOUND) += sound.o
obj-$(CONFIG_JZ_SFC) += spi_bus.o
obj-$(CONFIG_SPI_GPIO) += spi_bus.o
obj-$(CONFIG_I2C2_DMA_V12) += i2c_bus.o
obj-$(CONFIG_I2C_GPIO)          += i2c_bus.o
obj-$(CONFIG_I2C0_V12_JZ)       += i2c_bus.o
obj-$(CONFIG_I2C1_V12_JZ)       += i2c_bus.o
obj-$(CONFIG_I2C2_V12_JZ)       += i2c_bus.o
obj-$(CONFIG_I2C3_V12_JZ)       += i2c_bus.o
obj-$(CONFIG_JZMMC_V12) += mmc.o
obj-$(CONFIG_BCMDHD_43362) 		+= ap6181_wlan_power_control.o ap6181_wlan_device.o
